In [5]:
import numpy as np
import numpy.linalg as la
import math as mt

# Aufgabe 3

### A

In [ ]:
A = np.array([
    [1, mt.sqrt(2), -1],
    [-mt.sqrt(2), 0, -mt.sqrt(2)],
    [-1, mt.sqrt(2), 1]
])

A = A*0.5

A_T = A.T #get transpond-matrix

A_I = la.inv(A) #get inverse-matrix


print(A_T)
print("-----------------") # orthogonal, da gleich
print(A_I)

[[ 0.5        -0.70710678 -0.5       ]
 [ 0.70710678  0.          0.70710678]
 [-0.5        -0.70710678  0.5       ]]
-----------------
[[ 0.5        -0.70710678 -0.5       ]
 [ 0.70710678  0.          0.70710678]
 [-0.5        -0.70710678  0.5       ]]


### B

In [ ]:
A = np.array([
    [1, mt.sqrt(2), -1],
    [-mt.sqrt(2), 0, -mt.sqrt(2)],
    [-1, mt.sqrt(2), 1]
])

A = A*0.25

A_T = A.T #get transpond-matrix

A_I = la.inv(A) #get inverse-matrix


print(A_T)
print("-----------------") # nicht orthogonal, da nicht gleich
print(A_I) 

[[ 0.25       -0.35355339 -0.25      ]
 [ 0.35355339  0.          0.35355339]
 [-0.25       -0.35355339  0.25      ]]
-----------------
[[ 1.         -1.41421356 -1.        ]
 [ 1.41421356  0.          1.41421356]
 [-1.         -1.41421356  1.        ]]


### C

In [13]:
A = np.array([
    [1, mt.sqrt(2), 1],
    [-mt.sqrt(2), 0, -mt.sqrt(2)],
    [-1, mt.sqrt(2), 1]
])

A = A*0.5

A_T = A.T #get transpond-matrix

A_I = la.inv(A) #get inverse-matrix


print(A_T)
print("-----------------") # nicht orthogonal, da nicht gleich
print(A_I) 

[[ 0.5        -0.70710678 -0.5       ]
 [ 0.70710678  0.          0.70710678]
 [ 0.5        -0.70710678  0.5       ]]
-----------------
[[ 1.         -0.         -1.        ]
 [ 1.41421356  1.          0.        ]
 [-1.         -1.41421356  1.        ]]
