In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
A = np.array ([
    [ 1,  1],
    [-1, -1]
])
print (A)

[[ 1  1]
 [-1 -1]]


In [3]:
U, D, VT = la.svd (A)

In [4]:
print (U)

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [5]:
print (D)

[2.00000000e+00 3.35470445e-17]


In [6]:
Sigma = np.diag (D)
print (Sigma)

[[2.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.35470445e-17]]


In [7]:
print (VT)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [8]:
U_r = U [:, 0:1]
print (U_r)

[[-0.70710678]
 [ 0.70710678]]


In [9]:
Sigma_r = Sigma [0:1, 0:1]
print (Sigma_r)

[[2.]]


In [10]:
VT_r = VT [0:1, :]
print (VT_r)

[[-0.70710678 -0.70710678]]
