In [72]:
import numpy as np
import numpy.linalg as la
import math as mt

# Aufgabe 1

In [73]:
X_Dach_T = np.array ([[0, 1, 1, 2, 2, 3, 3, 4, 4, 5 ], 
               [0, 1, 2, 1, 3, 2, 4, 3, 4, 5]])

In [74]:
A = np.array([
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1]
])

In [75]:
I = np.eye(X_Dach_T.shape[1]) #Einheitsmatrix

In [76]:
M = I - 0.1 * A @ A.T
print("M: " , M)

M:  [[ 0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9]]


In [77]:
X = M @ X_Dach_T.T
print("X: ", X)

X:  [[-2.5 -2.5]
 [-1.5 -1.5]
 [-1.5 -0.5]
 [-0.5 -1.5]
 [-0.5  0.5]
 [ 0.5 -0.5]
 [ 0.5  1.5]
 [ 1.5  0.5]
 [ 1.5  1.5]
 [ 2.5  2.5]]


# Aufgabe 2

In [78]:
X_C = M @ X

In [79]:
C = 1/(10-1) * X_C.T @ X_C # 10 ist m (Zeilen von X)
print("C :", C)

C : [[2.5        2.16666667]
 [2.16666667 2.5       ]]


# Aufgabe 3 

In [80]:
#Eigenvektoren berechnen
w, eigenVec = la.eig(C)

In [81]:
# Eigenvektoren normieren
idx = np.argsort(w)[::-1] # nach grösse sortieren
w = w[idx]
eigenVec = eigenVec[:, idx]

v1 = eigenVec[:, 0] / np.linalg.norm(eigenVec[:, 0])
v2 = eigenVec[:, 1] / np.linalg.norm(eigenVec[:, 1])
V  = np.column_stack((v1, v2)) 

print("v1 =", v1)
print("v2 =", v2)

v1 = [-0.70710678 -0.70710678]
v2 = [-0.70710678  0.70710678]


In [82]:
Lambda = np.diag(w)
print(Lambda)

[[4.66666667 0.        ]
 [0.         0.33333333]]


In [83]:
V = np.column_stack((v1, v2))
print("U =\n", V)

U =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [84]:
C_rec = V @ Lambda @ V.T # V.T = la.inv(V)
print("C_rec ", C_rec)

C_rec  [[2.5        2.16666667]
 [2.16666667 2.5       ]]


# Aufgabe 4

In [85]:
A = np.array([
    [-2.5, -2.5],
    [-1.5, -1.5],
    [-1.5, -0.5],
    [-0.5, -1.5],
    [-0.5,  0.5],
    [ 0.5, -0.5],
    [ 0.5,  1.5],
    [ 1.5,  0.5],
    [ 1.5,  1.5],
    [ 2.5,  2.5]
])

# Aufgabe 5

In [86]:
A = np.array([
    [1],
    [2]
])

In [90]:
U, s, Vt = np.linalg.svd(A, full_matrices=False)   # Standard: „volle“ SVD

print("U =\n", np.round(U, 2))
print("s =", np.round(s, 2))
print("Vt =\n", np.round(Vt, 2))
print("Rekonstruktion =\n", np.round(result, 2))

U =
 [[0.45]
 [0.89]]
s = [2.24]
Vt =
 [[1.]]
Rekonstruktion =
 [[1.]
 [2.]]


In [91]:
Sigma_pseudo = np.diag(1 / s) 
print("Sigma =\n", Sigma_pseudo)

Sigma =
 [[0.4472136]]


In [93]:
A_pseudo = Vt.T @ Sigma_pseudo @ U.T
print("A_pseudo ", A_pseudo)

A_pseudo  [[0.2 0.4]]
