In [12]:
import numpy as np
import numpy.linalg as la

In [13]:
A = np.array ([
    [ 1,  1],
    [-1, -1]
])

In [17]:
U = np.array ([
    [-1, 1],
    [ 1, 1]
]) / np.sqrt (2)
U

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])

In [19]:
Sigma = np.array ([
    [2, 0],
    [0, 0]
])
Sigma

array([[2, 0],
       [0, 0]])

In [20]:
V = np.array ([
    [-1, -1],
    [ -1, 1]
]) / np.sqrt (2)
V

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [21]:
U @ Sigma @ V.T

array([[ 1.,  1.],
       [-1., -1.]])

In [22]:
Ur = np.array ([
    [-1],
    [ 1]
]) / np.sqrt (2)
Ur

array([[-0.70710678],
       [ 0.70710678]])

In [23]:
SigmaR = np.array ([
    [2]
])
SigmaR

array([[2]])

In [28]:
Vr = np.array ([
    [-1], 
    [-1]
]) / np.sqrt (2)
Vr

array([[-0.70710678],
       [-0.70710678]])

In [29]:
Ur @ SigmaR @ Vr.T

array([[ 1.,  1.],
       [-1., -1.]])