In [1]:
import numpy as np
import numpy.linalg as la
import math as mt

# Aufgabe 1

In [2]:
X_Dach_T = np.array ([[0, 1, 1, 2, 2, 3, 3, 4, 4, 5 ], 
               [0, 1, 2, 1, 3, 2, 4, 3, 4, 5]])

In [8]:
I = np.eye(X_Dach_T.shape[1]) #Einheitsmatrix

In [9]:
A = np.array([
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1]
])

In [10]:
M = I - 0.1 * A @ A.T
print(M)

[[ 0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9]]


In [11]:
X = M @ X_Dach_T.T
print(X)

[[-2.5 -2.5]
 [-1.5 -1.5]
 [-1.5 -0.5]
 [-0.5 -1.5]
 [-0.5  0.5]
 [ 0.5 -0.5]
 [ 0.5  1.5]
 [ 1.5  0.5]
 [ 1.5  1.5]
 [ 2.5  2.5]]


# Aufgabe 2

In [12]:
C = 1/(X_Dach_T.shape[1]-1) * X.T @ X
print(C)

[[2.5        2.16666667]
 [2.16666667 2.5       ]]


# Aufgabe 3