# Aufgabe 2

In [151]:
import numpy as np
import numpy.linalg as la
import math as mt

In [152]:
A = np.array ([[1, 2], # Singulär, da beide Zeilen Identisch
               [3, 6]])

In [153]:
I = np.array ([[1, 0],
               [0, 1]]) 

In [154]:
ATA = A.T @ A 
print(ATA)

[[10 20]
 [20 40]]


In [155]:
#Eigenvektoren berechnen
w, eigenVec = la.eig(ATA)

In [156]:
# Eigenvektoren normieren
idx = np.argsort(w)[::-1] # nach grösse sortieren
w = w[idx]
eigenVec = eigenVec[:, idx]

v1 = eigenVec[:, 0] / np.linalg.norm(eigenVec[:, 0])
v2 = eigenVec[:, 1] / np.linalg.norm(eigenVec[:, 1])
V  = np.column_stack((v1, v2)) 

print("v1 =", v1)
print("v2 =", v2)

v1 = [-0.4472136  -0.89442719]
v2 = [-0.89442719  0.4472136 ]


In [157]:
Sigma = np.diag(np.sqrt(w))
print(Sigma)

[[7.07106781 0.        ]
 [0.         0.        ]]


In [158]:
sigma1 = np.sqrt(w[0])      # größter Singularwert

u1 = (A @ v1) / sigma1 

u2 = np.array([-u1[1], u1[0]]) # beliebiger normierte Vektor, der orthogonal zu u1 ist.
u2 = u2 / np.linalg.norm(u2)

print("u1 =", u1)
print("u2 =", u2)

u1 = [-0.31622777 -0.9486833 ]
u2 = [ 0.9486833  -0.31622777]


In [159]:
U = np.column_stack((u1, u2))
print("U =\n", U)

U =
 [[-0.31622777  0.9486833 ]
 [-0.9486833  -0.31622777]]


In [160]:
result = U @ Sigma @ V.T

print("A =\n", A)
print("Lösung =\n", result)

A =
 [[1 2]
 [3 6]]
Lösung =
 [[1. 2.]
 [3. 6.]]


# Aufgabe 3

In [161]:
A = np.array ([[1, 1, 0], # Singulär, da beide Zeilen Identisch
               [0, 1, 1]])

In [162]:
ATA = A.T @ A
print(ATA)

[[1 1 0]
 [1 2 1]
 [0 1 1]]


In [163]:
#Eigenvektoren berechnen
w, eigenVec = la.eig(ATA)

In [164]:
# Eigenvektoren normieren
idx = np.argsort(w)[::-1] # nach grösse sortieren
w = w[idx]
eigenVec = eigenVec[:, idx]

v1 = eigenVec[:, 0] / np.linalg.norm(eigenVec[:, 0])
v2 = eigenVec[:, 1] / np.linalg.norm(eigenVec[:, 1])
V  = np.column_stack((v1, v2)) 

print("v1 =", v1)
print("v2 =", v2)

v1 = [-0.40824829 -0.81649658 -0.40824829]
v2 = [ 7.07106781e-01  3.06694063e-16 -7.07106781e-01]


In [165]:
sing = np.sqrt(w)           # alle σ_i
Sigma = np.diag(sing[:2])   # 2x2-Matrix für reduzierte SVD
print("Sigma =\n", Sigma)

Sigma =
 [[1.73205081 0.        ]
 [0.         1.        ]]


/var/folders/pw/48k2n0hs4n90dhyt6qd0xc040000gn/T/ipykernel_12382/2542027040.py:1: RuntimeWarning: invalid value encountered in sqrt
  sing = np.sqrt(w)           # alle σ_i


In [169]:
sigma1 = sing[0]
sigma2 = sing[1]

u1 = (A @ v1) / sigma1
u2 = (A @ v2) / sigma2

print("u1 =", u1)
print("u2 =", u2)

u1 = [-0.70710678 -0.70710678]
u2 = [ 0.70710678 -0.70710678]


In [170]:
U = np.column_stack((u1, u2))
print("U =\n", U)

U =
 [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [173]:
result = U @ Sigma @ V.T

print("A =\n", A)
print("Lösung =\n", np.round(result,2))

A =
 [[1. 1. 0.]
 [0. 1. 1.]]
Lösung =
 [[1. 1. 0.]
 [0. 1. 1.]]


# Aufgabe 3

In [174]:
A = np.array ([[2, 4], 
               [1, 3],
               [0, 0],
               [0, 0]])

In [176]:
U, s, Vt = np.linalg.svd(A)   # Standard: „volle“ SVD

Sigma = np.zeros((4, 2))
Sigma[:len(s), :len(s)] = np.diag(s)  # Sigma als 2x3 bauen

result = U @ Sigma @ Vt

print("U =\n", np.round(U, 2))
print("s =", np.round(s, 2))
print("Vt =\n", np.round(Vt, 2))
print("Rekonstruktion =\n", np.round(result, 2))

U =
 [[-0.82 -0.58  0.    0.  ]
 [-0.58  0.82  0.    0.  ]
 [ 0.    0.    1.    0.  ]
 [ 0.    0.    0.    1.  ]]
s = [5.46 0.37]
Vt =
 [[-0.4  -0.91]
 [-0.91  0.4 ]]
Rekonstruktion =
 [[2. 4.]
 [1. 3.]
 [0. 0.]
 [0. 0.]]
