In [1]:
import numpy as np
import matplotlib.pyplot as pl

In [2]:
A = np.array ([
    [1, 2],
    [2, 4],
    [3, 6]
])
print (A)

[[1 2]
 [2 4]
 [3 6]]


In [3]:
U, D, VT = np.linalg.svd (A)
Sigma = np.diag (D)
print (U)
print (Sigma)
print (VT)

[[-0.26726124  0.95618289  0.11952286]
 [-0.53452248 -0.04390192 -0.84401323]
 [-0.80178373 -0.28945968  0.52283453]]
[[8.36660027e+00 0.00000000e+00]
 [0.00000000e+00 8.88178420e-16]]
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]


In [4]:
B = np.array ([
    [1, 0, 0, 0, 2],
    [0, 0, 3, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 2, 0, 0, 0]
])
print (B)

[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 2 0 0 0]]


In [5]:
U, D, VT = np.linalg.svd (B)
Sigma = np.diag (D)
print (U)
print (Sigma)
print (VT)

[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]]
[[3.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.        ]
 [0.         0.         2.         0.        ]
 [0.         0.         0.         0.        ]]
[[-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [ 0.         -1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]
