In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
A = np.array ([
    [ 4, 4],
    [-3, 3]
])

In [3]:
U0, sigma0, V0T = la.svd (A)
V0 = V0T.T

In [4]:
U0

array([[-1.00000000e+00, -3.70074342e-18],
       [ 3.70074342e-18,  1.00000000e+00]])

In [5]:
Sigma0 = np.diag (sigma0)
Sigma0

array([[5.65685425, 0.        ],
       [0.        , 4.24264069]])

In [6]:
V0

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [7]:
U0 @ Sigma0 @ V0.T

array([[ 4.,  4.],
       [-3.,  3.]])

In [8]:
U0 @ Sigma0 @ V0.T - A

array([[-8.8817842e-16, -8.8817842e-16],
       [ 4.4408921e-16, -4.4408921e-16]])

In [9]:
EW1, EV1 = la.eig (A @ A.T)

In [10]:
U1 = EV1
U1

array([[1., 0.],
       [0., 1.]])

In [11]:
Sigma1 = np.diag (np.sqrt (EW1))
Sigma1

array([[5.65685425, 0.        ],
       [0.        , 4.24264069]])

In [12]:
V1 = A.T @ U1 @ la.inv (Sigma1)
V1

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [13]:
U1 @ Sigma1 @ V1.T

array([[ 4.,  4.],
       [-3.,  3.]])

In [14]:
U1 @ Sigma1 @ V1.T - A

array([[0., 0.],
       [0., 0.]])

In [15]:
EW2, EV2 = la.eig (A.T @ A)

In [16]:
V2 = EV2
V2

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [17]:
Sigma2 = np.diag (np.sqrt (EW2))
Sigma2

array([[5.65685425, 0.        ],
       [0.        , 4.24264069]])

In [18]:
U2 = A @ V2 @ la.inv (Sigma2)
U2

array([[1., 0.],
       [0., 1.]])

In [19]:
U2 @ Sigma2 @ V2.T

array([[ 4.,  4.],
       [-3.,  3.]])

In [20]:
U2 @ Sigma2 @ V2.T - A

array([[-8.8817842e-16, -8.8817842e-16],
       [ 4.4408921e-16, -4.4408921e-16]])

In [21]:
U0

array([[-1.00000000e+00, -3.70074342e-18],
       [ 3.70074342e-18,  1.00000000e+00]])

In [22]:
U1

array([[1., 0.],
       [0., 1.]])

In [23]:
U2

array([[1., 0.],
       [0., 1.]])

In [24]:
V0

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [25]:
V1

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [26]:
V2

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])