# Aufgabe 3

In [72]:
import numpy as np
import numpy.linalg as la
import math as mt

In [73]:
X = np.array([
    [1, 1, 1],
    [1, 2, 1],
    [1, 2, 2],
    [1, 1, 2]
])

In [74]:
y = np.array([[1], [2], [3], [3]])

### b

In [75]:
result = X.T @ X
print(result)

[[ 4  6  6]
 [ 6 10  9]
 [ 6  9 10]]


### C

In [76]:
b = la.pinv(X.T @ X) @ X.T @ y
print(b)

[[-0.75]
 [ 0.5 ]
 [ 1.5 ]]


### D

In [77]:
I = np.eye(X.shape[0]) #Einheitsmatrix
A = np.ones((4, 4)) # Matrix gefüllt mit 1

In [78]:
P = X @ la.pinv(X.T @ X) @ X.T
print("P", P)

Q = I - P
print("Q", Q)

M = I - (1/4) * A
print("M", M)


P [[ 0.75  0.25 -0.25  0.25]
 [ 0.25  0.75  0.25 -0.25]
 [-0.25  0.25  0.75  0.25]
 [ 0.25 -0.25  0.25  0.75]]
Q [[ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]]
M [[ 0.75 -0.25 -0.25 -0.25]
 [-0.25  0.75 -0.25 -0.25]
 [-0.25 -0.25  0.75 -0.25]
 [-0.25 -0.25 -0.25  0.75]]


### E

In [79]:
y_dach = P @ y
print(y_dach)

e1 = Q @ y
print("e1", e1)

e2 = y - y_dach
print("e2", e1)

[[1.25]
 [1.75]
 [3.25]
 [2.75]]
e1 [[-0.25]
 [ 0.25]
 [-0.25]
 [ 0.25]]
e2 [[-0.25]
 [ 0.25]
 [-0.25]
 [ 0.25]]


### F

In [82]:
SQR = float(y.T @ Q @ y)    
SQT = float(y.T @ M @ y)
R2 = 1 - SQR / SQT
print(mt.sqrt(R2))

0.9534625892455889


/var/folders/pw/48k2n0hs4n90dhyt6qd0xc040000gn/T/ipykernel_1662/2425295611.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  SQR = float(y.T @ Q @ y)
/var/folders/pw/48k2n0hs4n90dhyt6qd0xc040000gn/T/ipykernel_1662/2425295611.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  SQT = float(y.T @ M @ y)
