In [1]:
import numpy as np
import numpy.linalg as la
import math as mt

In [2]:
A = np.array([
    [5,   1],
    [0, 4]
])

In [3]:
#Eigenvektoren berechnen
w, eigenVec = la.eig(A)

In [4]:
# Eigenvektoren normieren
idx = np.argsort(w)[::-1] # nach grösse sortieren
w = w[idx]
eigenVec = eigenVec[:, idx]

v1 = eigenVec[:, 0] / np.linalg.norm(eigenVec[:, 0])
v2 = eigenVec[:, 1] / np.linalg.norm(eigenVec[:, 1])
V  = np.column_stack((v1, v2)) 

print("v1 =", v1)
print("v2 =", v2)

v1 = [1. 0.]
v2 = [-0.70710678  0.70710678]


In [5]:
Lambda = np.diag(w)
print(Lambda)

[[5. 0.]
 [0. 4.]]


In [6]:
V = np.column_stack((v1, v2))
print("V =\n", np.round(V, 2))

V =
 [[ 1.   -0.71]
 [ 0.    0.71]]


In [8]:
A_rec = V @ Lambda @ la.inv(V)
print("A_rec ")
print(A_rec)
print(la.inv(V))

A_rec 
[[5. 1.]
 [0. 4.]]
[[1.         1.        ]
 [0.         1.41421356]]
