In [96]:
import numpy as np
import numpy.linalg as la
import math as mt

In [97]:
A = np.array ([[1, 2], # Singulär, da beide Zeilen Identisch
               [3, 6]])

In [98]:
ATA = A.T @ A
print("ATA:")
print(ATA)

ATA:
[[10 20]
 [20 40]]


In [99]:
#Eigenvektoren berechnen
w, eigenVec = la.eig(ATA)

# Eigenvektoren normieren
idx = np.argsort(w)[::-1] # nach grösse sortieren
w = w[idx]
eigenVec = eigenVec[:, idx]

v1 = eigenVec[:, 0] / np.linalg.norm(eigenVec[:, 0])
v2 = eigenVec[:, 1] / np.linalg.norm(eigenVec[:, 1])
V  = np.column_stack((v1, v2)) 

print("v1 =", v1)
print("v2 =", v2)
print("V =\n", v2)

v1 = [-0.4472136  -0.89442719]
v2 = [-0.89442719  0.4472136 ]
V =
 [-0.89442719  0.4472136 ]


In [100]:
sing = np.sqrt(w)           # alle σ_i
Sigma = np.diag(sing[:2])   # 2x2-Matrix für reduzierte SVD
print("Sigma =\n", Sigma)

Sigma =
 [[7.07106781 0.        ]
 [0.         0.        ]]


In [101]:
sigma1 = sing[0]
sigma2 = sing[1]

tol = 1e-12

# u1 (nur wenn sigma1 > 0)
if abs(sigma1) < tol:
    raise ValueError("sigma1 ist ~0, u1 kann nicht via (A@v1)/sigma1 berechnet werden.")
u1 = (A @ v1) / sigma1
u1 = u1 / np.linalg.norm(u1)  # optional: stabil normieren

# u2 (wenn sigma2 == 0 -> orthogonale Ergänzung statt Division)
if abs(sigma2) > tol:
    u2 = (A @ v2) / sigma2
    u2 = u2 / np.linalg.norm(u2)  # optional
else:
    # beliebiger Vektor orthogonal zu u1 (allgemein für m-dim)
    r = np.random.randn(u1.size)
    r = r - u1 * (u1 @ r)          # projiziere Anteil auf u1 weg
    nr = np.linalg.norm(r)
    if nr < tol:                   # sehr unwahrscheinlich, aber safe
        r = np.roll(u1, 1)
        r = r - u1 * (u1 @ r)
        nr = np.linalg.norm(r)
    u2 = r / nr

U = np.column_stack((u1, u2))


print("u1 =", u1)
print("u2 =", u2)
print("U =\n", U)

u1 = [-0.31622777 -0.9486833 ]
u2 = [ 0.9486833  -0.31622777]
U =
 [[-0.31622777  0.9486833 ]
 [-0.9486833  -0.31622777]]


In [102]:
result = U @ Sigma @ V.T

print("A =\n", A)
print("Lösung =\n", np.round(result,2))

A =
 [[1 2]
 [3 6]]
Lösung =
 [[1. 2.]
 [3. 6.]]


# Kontrolle

In [103]:
U, s, Vt = np.linalg.svd(A)   # Standard: „volle“ SVD

Sigma = np.zeros((2, 2)) # Dimensionen der Matrix eintragen! (Zeilen, Spalten)
Sigma[:len(s), :len(s)] = np.diag(s)  

result = U @ Sigma @ Vt

print("U =\n", np.round(U, 2))
print("Sigma =\n", np.round(Sigma, 2))
print("V_T =\n", np.round(Vt, 2))
print("Rekonstruktion =\n", np.round(result, 2))

U =
 [[-0.32 -0.95]
 [-0.95  0.32]]
Sigma =
 [[7.07 0.  ]
 [0.   0.  ]]
V_T =
 [[-0.45 -0.89]
 [-0.89  0.45]]
Rekonstruktion =
 [[1. 2.]
 [3. 6.]]
