In [ ]:
import numpy as np
import numpy.linalg as la

"""
Exercise 5.1

Check whether the lines g and h intersect.
If they do, calculate the intersection point and the angle of intersection.

g : r = (6, 3, 2) + λ (4, 2, -1)
h : r = (-3, 3, 0) + μ (5, -2, 3)
"""

In [2]:
p = np.array ([
    [6],
    [3],
    [2]
])

In [3]:
u = np.array ([
    [ 4],
    [ 2],
    [-1]
])

In [4]:
q = np.array ([
    [-3],
    [ 3],
    [ 0]
])

In [5]:
v = np.array ([
    [ 5],
    [-2],
    [ 3]
])

In [6]:
A3 = np.concatenate ((u, -v), axis = 1)
print (A3)

[[ 4 -5]
 [ 2  2]
 [-1 -3]]


In [7]:
A = A3 [0:2, 0:2]
print (A)

[[ 4 -5]
 [ 2  2]]


In [8]:
b3 = q - p
print (b3)

[[-9]
 [ 0]
 [-2]]


In [9]:
b = b3 [0:2, 0:1]
print (b)

[[-9]
 [ 0]]


In [ ]:
#Schnittpunkt
[s, t] = la.solve (A, b)
print (s)
print (t)

[-1.]
[1.]


In [11]:
p + s * u

array([[2.],
       [1.],
       [3.]])

In [12]:
q + t * v

array([[2.],
       [1.],
       [3.]])

In [13]:
def dot (u, v):
    return np.sum (u * v)

In [14]:
c = dot (u, v) / (la.norm (u) * la.norm (v))
print (c)

0.4601950115131127


In [15]:
b = np.arccos (c)
print (b)

1.0925814881636011


In [ ]:
#Schnittwinkel
w = b * 180 / np.pi
print (w)

62.60030804589706
