In [49]:
import numpy as np
import numpy.linalg as la
import math as mt

# Eingabe

In [50]:
X_dach = np.array ([
    [0, 0],
    [1, 1],
    [1, 2],
    [2, 1],
    [2, 3],
    [3, 2],
    [3, 4],
    [4, 3],
    [4, 4],
    [5, 5]
])

In [51]:
m = 10 # Anzahl Zeilen von X_dach

# Zentrierungsmatrix M

In [52]:
I = np.eye(m) #Einheitsmatrix

In [53]:
Ones = np.array([
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1],
    [1]
])

In [54]:
M = I - 0.1 * Ones @ Ones.T
print("Zentrierungsmatrix M:")
print(M)

Zentrierungsmatrix M:
[[ 0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9 -0.1]
 [-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1  0.9]]


# Zentriertre Matrix XC

In [55]:
XC = M @  X_dach
print("XC:")
print(XC)

XC:
[[-2.5 -2.5]
 [-1.5 -1.5]
 [-1.5 -0.5]
 [-0.5 -1.5]
 [-0.5  0.5]
 [ 0.5 -0.5]
 [ 0.5  1.5]
 [ 1.5  0.5]
 [ 1.5  1.5]
 [ 2.5  2.5]]


# Kovarianzmatrix

In [57]:
C = 1/(m-1) * XC.T @ XC
print("C:")
print(np.round(C, 3))

C:
[[2.5   2.167]
 [2.167 2.5  ]]
