In [31]:
import numpy as np
import numpy.linalg as la
import math as mt

# Eingabe

In [32]:
X_dach = np.array ([
    [6, 7],
    [4, -7],
    [1, -6],
    [9, -2]
])

In [33]:
m = 4 # Anzahl Zeilen von X_dach

# Zentrierungsmatrix M

In [34]:
I = np.eye(m) #Einheitsmatrix

In [35]:
Ones = np.array([
    [1],
    [1],
    [1],
    [1]
])

In [36]:
M = I - (1/m) * Ones @ Ones.T
print("Zentrierungsmatrix M:")
print(M)

Zentrierungsmatrix M:
[[ 0.75 -0.25 -0.25 -0.25]
 [-0.25  0.75 -0.25 -0.25]
 [-0.25 -0.25  0.75 -0.25]
 [-0.25 -0.25 -0.25  0.75]]


# Zentriertre Matrix XC

In [37]:
XC = M @  X_dach
print("XC:")
print(XC)

XC:
[[ 1.  9.]
 [-1. -5.]
 [-4. -4.]
 [ 4.  0.]]


# Kovarianzmatrix

In [38]:
C = 1/(m-1) * XC.T @ XC
print("C:")
print(np.round(C, 3))

C:
[[11.333 10.   ]
 [10.    40.667]]
