In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
A = np.array ([
    [ 1, 2, 1],
    [ 2, 1, 0],
    [-3, 0, 9.]
])
A

array([[ 1.,  2.,  1.],
       [ 2.,  1.,  0.],
       [-3.,  0.,  9.]])

In [3]:
E21 = np.array ([
    [ 1, 0, 0],
    [-2, 1, 0],
    [ 0, 0, 1.]
])
E21

array([[ 1.,  0.,  0.],
       [-2.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [4]:
E21 @ A

array([[ 1.,  2.,  1.],
       [ 0., -3., -2.],
       [-3.,  0.,  9.]])

In [5]:
E31 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [3, 0, 1.]
])
E31 @ E21 @ A

array([[ 1.,  2.,  1.],
       [ 0., -3., -2.],
       [ 0.,  6., 12.]])

In [6]:
E32 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [0, 2, 1.]
])
R = E32 @ E31 @ E21 @ A
R

array([[ 1.,  2.,  1.],
       [ 0., -3., -2.],
       [ 0.,  0.,  8.]])

In [7]:
E21

array([[ 1.,  0.,  0.],
       [-2.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
la.inv (E21)

array([[ 1., -0., -0.],
       [ 2.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
la.inv (E31)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-3., -0.,  1.]])

In [10]:
la.inv (E32)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-0., -2.,  1.]])

In [11]:
L = la.inv (E21) @ la.inv (E31) @ la.inv (E32)
L

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  0.],
       [-3., -2.,  1.]])

In [12]:
L @ R

array([[ 1.,  2.,  1.],
       [ 2.,  1.,  0.],
       [-3.,  0.,  9.]])

In [13]:
A

array([[ 1.,  2.,  1.],
       [ 2.,  1.,  0.],
       [-3.,  0.,  9.]])

In [14]:
L @ R - A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.max (np.abs (L @ R - A))

np.float64(0.0)