# Lineare Algebra - SW 04 - Übungen

In [2]:
import numpy as np
import numpy.linalg as la

## Aufgabe 1

### A

In [4]:
A = np.array ([[4, 3], [8, 6]])
print (la.det (A))

0.0


### B

In [5]:
B = np.array ([[4, 3], [8, 7]])
print (la.det (B))

3.999999999999999


In [7]:
B_inv = la.inv(B)
print(B_inv)

[[ 1.75 -0.75]
 [-2.    1.  ]]


### C

In [8]:
C = np.array ([[6, 6], [6, 6]])
print (la.det (C))

0.0


### D

In [9]:
D = np.array ([[1, 0, 0], [ 1, 1, 0], [ 1, 1, 1]])
print (la.det (D))

1.0


In [10]:
D_inv = la.inv(D)
print(D_inv)

[[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 0. -1.  1.]]


## Aufgabe 2

### A

In [13]:
A = np.array ([[0, 3], [4, 0]])
print (la.det (A))

-12.0


In [14]:
A_inv = la.inv(A)
print(A_inv)

[[0.         0.25      ]
 [0.33333333 0.        ]]
