In [15]:
import numpy as np

In [16]:
A = np.array ([
    [6, -1, -1,  4],
    [1,  1, 10, -6],
    [2, -1,  1, -2]
])
print (A)

[[ 6 -1 -1  4]
 [ 1  1 10 -6]
 [ 2 -1  1 -2]]


In [17]:
np.linalg.solve (A [0:3, 0:3], A [0:3, 3:4])

array([[ 1.],
       [ 3.],
       [-1.]])

In [18]:
P = np.array ([
    [0, 1, 0],
    [1, 0, 0],
    [0, 0, 1]
])
print (P)

[[0 1 0]
 [1 0 0]
 [0 0 1]]


In [19]:
A = P @ A
print (A)

[[ 1  1 10 -6]
 [ 6 -1 -1  4]
 [ 2 -1  1 -2]]


In [20]:
A [1] = A [1] - 6 * A [0]
print (A)

[[  1   1  10  -6]
 [  0  -7 -61  40]
 [  2  -1   1  -2]]


In [21]:
A [2] = A [2] - 2 * A [0]
print (A)

[[  1   1  10  -6]
 [  0  -7 -61  40]
 [  0  -3 -19  10]]


In [22]:
A [2] = 7 * A [2] - 3 * A [1]
print (A)

[[  1   1  10  -6]
 [  0  -7 -61  40]
 [  0   0  50 -50]]


In [23]:
A [2] = A [2] / 50
print (A)

[[  1   1  10  -6]
 [  0  -7 -61  40]
 [  0   0   1  -1]]


In [24]:
A [1] = A [1] + 61 * A [2]
print (A)

[[  1   1  10  -6]
 [  0  -7   0 -21]
 [  0   0   1  -1]]


In [25]:
A [0] = A [0] - 10 * A [2]
print (A)

[[  1   1   0   4]
 [  0  -7   0 -21]
 [  0   0   1  -1]]


In [26]:
A [1] = A [1] / -7
print (A)

[[ 1  1  0  4]
 [ 0  1  0  3]
 [ 0  0  1 -1]]


In [27]:
A [0] = A [0] - A [1]
print (A)

[[ 1  0  0  1]
 [ 0  1  0  3]
 [ 0  0  1 -1]]
