In [1]:
import numpy as np

In [9]:
A = np.array ([
    [1, 1, 1, 0],
    [4, 2, 1, 1],
    [9, 3, 1, 3.]
])
print (A)

[[1. 1. 1. 0.]
 [4. 2. 1. 1.]
 [9. 3. 1. 3.]]


In [10]:
A [1] = A [1] - 4 * A [0]
print (A)

[[ 1.  1.  1.  0.]
 [ 0. -2. -3.  1.]
 [ 9.  3.  1.  3.]]


In [11]:
A [2] = A [2] - 9 * A [0]
print (A)

[[ 1.  1.  1.  0.]
 [ 0. -2. -3.  1.]
 [ 0. -6. -8.  3.]]


In [12]:
A [2] = A [2] - 3 * A [1]
print (A)

[[ 1.  1.  1.  0.]
 [ 0. -2. -3.  1.]
 [ 0.  0.  1.  0.]]


In [13]:
A [1] = A [1] + 3 * A [2]
print (A)

[[ 1.  1.  1.  0.]
 [ 0. -2.  0.  1.]
 [ 0.  0.  1.  0.]]


In [14]:
A [0] = A [0] - A [2]
print (A)

[[ 1.  1.  0.  0.]
 [ 0. -2.  0.  1.]
 [ 0.  0.  1.  0.]]


In [15]:
A [1] = A [1] / -2
print (A)

[[ 1.   1.   0.   0. ]
 [-0.   1.  -0.  -0.5]
 [ 0.   0.   1.   0. ]]


In [16]:
A [0] = A [0] - A [1]
print (A)

[[ 1.   0.   0.   0.5]
 [-0.   1.  -0.  -0.5]
 [ 0.   0.   1.   0. ]]
