In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
A = np.array ([
    [2, -1],
    [2, 2]
])

In [3]:
A

array([[ 2, -1],
       [ 2,  2]])

In [4]:
b = np.array ([
    [7],
    [1] 
])

In [5]:
b

array([[7],
       [1]])

In [6]:
x = la.solve (A, b)

In [7]:
x

array([[ 2.5],
       [-2. ]])

In [8]:
A @ x

array([[7.],
       [1.]])

In [9]:
p = np.array ([
    [1],
    [0],
    [2]
])

In [10]:
u = np.array ([
    [1],
    [2],
    [1]
])

In [11]:
q = np.array ([
    [2],
    [3],
    [1]
])

In [12]:
v = np.array ([
    [4],
    [2],
    [9]
])

In [13]:
w = np.array ([
    [3],
    [1],
    [6]
])

In [14]:
A = np.hstack ((u, -v, -w))
A

array([[ 1, -4, -3],
       [ 2, -2, -1],
       [ 1, -9, -6]])

In [15]:
b = q - p
b

array([[ 1],
       [ 3],
       [-1]])

In [16]:
x = la.solve (A, b)
x

array([[ 2.],
       [ 1.],
       [-1.]])

In [17]:
np.concatenate ((u, -v, -w), axis = 1)

array([[ 1, -4, -3],
       [ 2, -2, -1],
       [ 1, -9, -6]])

In [18]:
la.det (A)

np.float64(6.999999999999999)