In [1]:
import numpy as np

In [2]:
A = np.array ([
    [2, -1,  3, 4],
    [1,  0, -2, 7],
    [3, -3,  1, 5],
    [2,  1,  4, 4.]
])
print (A)

[[ 2. -1.  3.  4.]
 [ 1.  0. -2.  7.]
 [ 3. -3.  1.  5.]
 [ 2.  1.  4.  4.]]


In [3]:
b = np.array ([
    [ 9],
    [11],
    [ 8],
    [10.]
])
print (b)

[[ 9.]
 [11.]
 [ 8.]
 [10.]]


In [4]:
E21 = np.array ([
    [   1, 0, 0, 0],
    [-1/2, 1, 0, 0],
    [   0, 0, 1, 0],
    [   0, 0, 0, 1]
])
print (E21)

[[ 1.   0.   0.   0. ]
 [-0.5  1.   0.   0. ]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]


In [5]:
E21 @ A

array([[ 2. , -1. ,  3. ,  4. ],
       [ 0. ,  0.5, -3.5,  5. ],
       [ 3. , -3. ,  1. ,  5. ],
       [ 2. ,  1. ,  4. ,  4. ]])

In [6]:
E31 = np.array ([
    [   1, 0, 0, 0],
    [   0, 1, 0, 0],
    [-3/2, 0, 1, 0],
    [   0, 0, 0, 1]
])
print (E31)

[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [-1.5  0.   1.   0. ]
 [ 0.   0.   0.   1. ]]


In [7]:
E31 @ E21 @ A

array([[ 2. , -1. ,  3. ,  4. ],
       [ 0. ,  0.5, -3.5,  5. ],
       [ 0. , -1.5, -3.5, -1. ],
       [ 2. ,  1. ,  4. ,  4. ]])

In [8]:
E41 = np.array ([
    [ 1, 0, 0, 0],
    [ 0, 1, 0, 0],
    [ 0, 0, 1, 0],
    [-1, 0, 0, 1.]
])
print (E41)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-1.  0.  0.  1.]]


In [9]:
E41 @ E31 @ E21 @ A

array([[ 2. , -1. ,  3. ,  4. ],
       [ 0. ,  0.5, -3.5,  5. ],
       [ 0. , -1.5, -3.5, -1. ],
       [ 0. ,  2. ,  1. ,  0. ]])

In [10]:
E32 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 3, 1, 0],
    [0, 0, 0, 1.]
])
print (E32)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 3. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
E32 @ E41 @ E31 @ E21 @ A

array([[  2. ,  -1. ,   3. ,   4. ],
       [  0. ,   0.5,  -3.5,   5. ],
       [  0. ,   0. , -14. ,  14. ],
       [  0. ,   2. ,   1. ,   0. ]])

In [12]:
E42 = np.array ([
    [1,  0, 0, 0],
    [0,  1, 0, 0],
    [0,  0, 1, 0],
    [0, -4, 0, 1.]
])
print (E42)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -4.  0.  1.]]


In [13]:
E42 @ E32 @ E41 @ E31 @ E21 @ A

array([[  2. ,  -1. ,   3. ,   4. ],
       [  0. ,   0.5,  -3.5,   5. ],
       [  0. ,   0. , -14. ,  14. ],
       [  0. ,   0. ,  15. , -20. ]])

In [14]:
E43 = np.array ([
    [1, 0,     0, 0],
    [0, 1,     0, 0],
    [0, 0,     1, 0],
    [0, 0, 15/14, 1.]
])
print (E43)

[[1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.         1.07142857 1.        ]]


In [15]:
print (np.round (E43 @ E42 @ E32 @ E41 @ E31 @ E21 @ A, 10))

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.    0.   -5. ]]


In [16]:
U = E43 @ E42 @ E32 @ E41 @ E31 @ E21 @ A
print (np.round (U, 10))

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.    0.   -5. ]]


In [17]:
L = np.linalg.inv (E43 @ E42 @ E32 @ E41 @ E31 @ E21)
print (np.round (L, 10))

[[ 1.         -0.         -0.         -0.        ]
 [ 0.5         1.         -0.         -0.        ]
 [ 1.5        -3.          1.          0.        ]
 [ 1.          4.         -1.07142857  1.        ]]


In [18]:
print (L @ U)

[[ 2. -1.  3.  4.]
 [ 1.  0. -2.  7.]
 [ 3. -3.  1.  5.]
 [ 2.  1.  4.  4.]]


In [19]:
print (np.round (L @ U - A, 10))

[[ 0.  0.  0. -0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -0.]
 [ 0.  0. -0.  0.]]


In [20]:
y = np.linalg.inv (L) @ b
print (y)

[[  9. ]
 [  6.5]
 [ 14. ]
 [-10. ]]


In [21]:
x = np.linalg.inv (U) @ y
print (np.round (x, 10))

[[-1.]
 [-0.]
 [ 1.]
 [ 2.]]


In [22]:
print (A @ x)

[[ 9.]
 [11.]
 [ 8.]
 [10.]]


In [23]:
print (np.round (A @ x - b, 10))

[[-0.]
 [-0.]
 [ 0.]
 [-0.]]
