In [1]:
import numpy as np

In [2]:
A = np.array ([
    [ 1,  1, 2],
    [-1, -2, 3],
    [ 3, -7, 4.]
])
print (A)

[[ 1.  1.  2.]
 [-1. -2.  3.]
 [ 3. -7.  4.]]


In [3]:
b = np.array ([
    [8],
    [1],
    [10.]
])
print (b)

[[ 8.]
 [ 1.]
 [10.]]


In [4]:
E21 = np.array ([
    [1, 0, 0],
    [1, 1, 0],
    [0, 0, 1.]
])
print (E21)

[[1. 0. 0.]
 [1. 1. 0.]
 [0. 0. 1.]]


In [5]:
print (E21 @ A)

[[ 1.  1.  2.]
 [ 0. -1.  5.]
 [ 3. -7.  4.]]


In [6]:
E31 = np.array ([
    [ 1, 0, 0],
    [ 0, 1, 0],
    [-3, 0, 1.]
])
print (E31)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-3.  0.  1.]]


In [7]:
print (E31 @ E21 @ A)

[[  1.   1.   2.]
 [  0.  -1.   5.]
 [  0. -10.  -2.]]


In [8]:
E32 = np.array ([
    [1,   0, 0],
    [0,   1, 0],
    [0, -10, 1.]
])
print (E32)

[[  1.   0.   0.]
 [  0.   1.   0.]
 [  0. -10.   1.]]


In [9]:
print (np.round (E32 @ E31 @ E21 @ A))

[[  1.   1.   2.]
 [  0.  -1.   5.]
 [  0.   0. -52.]]


In [10]:
U = E32 @ E31 @ E21 @ A
print (np.round (U, 10))

[[  1.   1.   2.]
 [  0.  -1.   5.]
 [  0.   0. -52.]]


In [11]:
L = np.linalg.inv (E32 @ E31 @ E21)
print (np.round (L, 10))

[[ 1.  0.  0.]
 [-1.  1. -0.]
 [ 3. 10.  1.]]


In [12]:
print (L @ U)

[[ 1.  1.  2.]
 [-1. -2.  3.]
 [ 3. -7.  4.]]


In [13]:
print (np.round (L @ U - A, 10))

[[-0. -0.  0.]
 [ 0.  0.  0.]
 [-0. -0.  0.]]


In [14]:
y = np.linalg.inv (L) @ b
print (y)

[[   8.]
 [   9.]
 [-104.]]


In [15]:
x = np.linalg.inv (U) @ y
print (x)

[[3.]
 [1.]
 [2.]]


In [16]:
print (A @ x)

[[ 8.]
 [ 1.]
 [10.]]


In [17]:
print (A @ x - b)

[[ 0.00000000e+00]
 [ 5.32907052e-15]
 [-3.55271368e-14]]
