In [1]:
import numpy as np
import numpy.linalg as la

In [ ]:
p = np.array ([
    [3],
    [5],
    [4]
])

In [ ]:
u = np.array ([
    [4],
    [6],
    [4]
])

In [ ]:
q = np.array ([
    [8],
    [2],
    [7]
])

In [ ]:
v = np.array ([
    [3],
    [1],
    [5]
])

In [6]:
A3 = np.concatenate ((u, -v), axis = 1)
print (A3)

[[ 4 -3]
 [ 6 -1]
 [ 4 -5]]


In [7]:
A = A3 [0:2, 0:2]
print (A)

[[ 4 -3]
 [ 6 -1]]


In [8]:
b3 = q - p
print (b3)

[[ 5]
 [-3]
 [ 3]]


In [9]:
b = b3 [0:2, 0:1]
print (b)

[[ 5]
 [-3]]


In [14]:
[s, t] = la.solve (A, b)
print (s)
print (t)

[-1.]
[-3.]


In [11]:
p + s * u

array([[-1.],
       [-1.],
       [ 0.]])

In [13]:
q + t * v

array([[-1.],
       [-1.],
       [-8.]])