In [17]:
import numpy as np
import numpy.linalg as la

In [18]:
p = np.array ([
    [2],
    [3],
    [4.]
])
p

array([[2.],
       [3.],
       [4.]])

In [19]:
q = np.array ([
    [5],
    [3],
    [4.]
])
q

array([[5.],
       [3.],
       [4.]])

In [20]:
u = np.array ([
    [1],
    [2],
    [5.]
])
u

array([[1.],
       [2.],
       [5.]])

In [21]:
v = np.array ([
    [3],
    [4],
    [4.]
])
v

array([[3.],
       [4.],
       [4.]])

In [22]:
w = np.array ([
    [7],
    [3],
    [3.]
])
w

array([[7.],
       [3.],
       [3.]])

In [23]:
A = np.hstack ((u, v, -w))
A

array([[ 1.,  3., -7.],
       [ 2.,  4., -3.],
       [ 5.,  4., -3.]])

In [24]:
b = q - p
b

array([[3.],
       [0.],
       [0.]])

In [26]:
x = la.solve (A, b)
x

array([[-4.44089210e-17],
       [-4.73684211e-01],
       [-6.31578947e-01]])

In [28]:
[r, s, t] = x
print (r, s, t)

[-4.4408921e-17] [-0.47368421] [-0.63157895]


In [29]:
p + r * u + s * v

array([[0.57894737],
       [1.10526316],
       [2.10526316]])

In [30]:
q + t * w

array([[0.57894737],
       [1.10526316],
       [2.10526316]])